import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/global.css'
import Navabar from '@/components/Navabar'
import { Toaster } from '@/components/ui/toaster'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='h-screen flex flex-col justify-center items-center '>
          <Navabar />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  )
}
